Fixing FQL method
It seems that FQL API changed in the last year but facebook-sdk doesn't track these changes.

FQL queries work for regular accounts with current code but using the current endpoint yields an error for pages:
GraphAPIError: Impersonated access tokens can only be used with the Graph API

I fixed the problem by changing the endpoint and altering the parameter passed as documented here:
https://developers.facebook.com/docs/technical-guides/fql/